#! /usr/bin/env bash

set -euo pipefail

function compile-contract() {
    docker run -v ${PWD}/contracts:/project/contracts --rm -i ligolang/ligo:next \
        compile-contract --michelson-format=json \
         /project/contracts/${1} ${2}
}


function compile-contracts() {
    mkdir -p ./build/contracts
    compile-contract "Inventory.ligo" "main" > ${PWD}/build/contracts/inventory.json
    compile-contract "Warehouse.ligo" "main" > ${PWD}/build/contracts/warehouse.json
}

function prepare-dist() {
    mkdir -p ./dist
    cp -rf ./build/contracts/* ./dist
}

"$@"